#define ENTERO	   1
#define ID	   	   2
#define FLOTANTE   3
#define STRING	   4 
#define TIPO	   5 
#define EXPRESION  6 
#define TERMINO	   7 
#define ESCRITURA  8 
#define ASIGNACION 9
#define PROGRAM	   10
#define EXP	       11
#define CORCHETE_IZQ 12
#define CORCHETE_DER 13
#define PARENTESIS_IZQ 14
#define PARENTESIS_DER 15
#define PUNTO_COMA 16
#define ESPACIO    17
#define FIN_LINEA  18
#define TAB	       19
#define IF 		   20
#define ELSE	   21
#define COMA 	   22
#define VAR	       23