
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '9E2CC698B0EAE42C7AA21BE917D1F4BD'
    
_lr_action_items = {'EXPRESION':([31,32,34,35,36,38,39,47,56,58,60,],[-28,-33,-22,49,-24,-27,-26,-34,-32,-23,-25,]),'PARENTESIS_IZQ':([14,15,22,23,24,29,44,46,48,49,50,],[22,23,29,29,29,29,29,29,29,29,29,]),'TIPO':([25,],[42,]),'STRING':([22,44,46,],[30,30,30,]),'ASIGNACION':([16,19,],[24,25,]),'PARENTESIS_DER':([28,30,31,32,34,35,36,37,38,39,40,45,47,55,56,57,58,59,60,],[-16,-18,-28,-33,-22,-20,-24,51,-27,-26,52,56,-34,-17,-32,-19,-23,-21,-25,]),'PUNTO_COMA':([3,20,31,32,34,35,36,38,39,41,42,47,51,56,58,59,60,63,67,],[4,-8,-28,-33,-22,-20,-24,-27,-26,53,54,-34,61,-32,-23,-21,-25,65,68,]),'ELSE':([20,63,],[-8,66,]),'CORCHETE_DER':([10,11,12,13,17,21,53,61,62,65,68,],[20,-11,-9,-12,-13,-10,-14,-15,-29,-30,-31,]),'CORCHETE_IZQ':([4,5,18,26,43,52,54,64,66,],[6,6,-3,-4,-5,6,-7,-6,6,]),'COMA':([19,28,30,31,32,34,35,36,38,39,47,56,58,59,60,],[27,44,46,-28,-33,-22,-20,-24,-27,-26,-34,-32,-23,-21,-25,]),'ENTERO':([22,23,24,29,33,44,46,48,49,50,],[38,38,38,38,38,38,38,38,38,38,]),'PROGRAM':([0,],[2,]),'TERMINO':([31,32,36,38,39,47,56,],[-28,-33,50,-27,-26,-34,-32,]),'IF':([6,11,12,13,17,53,61,62,65,68,],[15,-11,15,-12,-13,-14,-15,-29,-30,-31,]),'FLOTANTE':([22,23,24,29,33,44,46,48,49,50,],[31,31,31,31,31,31,31,31,31,31,]),'VAR':([4,],[7,]),'EXP':([22,23,24,29,31,32,34,36,38,39,44,46,47,48,49,50,56,60,],[33,33,33,33,-28,-33,48,-24,-27,-26,33,33,-34,33,33,33,-32,-25,]),'ESCRITURA':([6,11,12,13,17,53,61,62,65,68,],[14,-11,14,-12,-13,-14,-15,-29,-30,-31,]),'ID':([2,6,7,11,12,13,17,22,23,24,27,29,33,44,46,48,49,50,53,54,61,62,65,68,],[3,16,19,-11,16,-12,-13,39,39,39,19,39,39,39,39,39,39,39,-14,19,-15,-29,-30,-31,]),'$end':([1,8,9,20,],[0,-2,-1,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([22,23,24,29,44,46,],[28,40,41,45,28,28,]),'bloque2':([6,12,],[10,21,]),'asignacion':([6,12,],[11,11,]),'vars':([4,],[5,]),'estatuto':([6,12,],[12,12,]),'condicion2':([52,],[62,]),'var_cte':([22,23,24,29,33,44,46,48,49,50,],[32,32,32,32,47,32,32,32,32,32,]),'vars3':([19,],[26,]),'vars2':([7,27,54,],[18,43,64,]),'program':([0,],[1,]),'termino':([22,23,24,29,44,46,48,49,],[34,34,34,34,34,34,58,34,]),'condicion':([6,12,],[13,13,]),'exp':([22,23,24,29,44,46,49,],[35,35,35,35,35,35,59,]),'factor':([22,23,24,29,44,46,48,49,50,],[36,36,36,36,36,36,36,36,60,]),'bloque':([4,5,52,66,],[8,9,63,67,]),'escritura2':([22,44,46,],[37,55,57,]),'escritura':([6,12,],[17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID PUNTO_COMA vars bloque','program',5,'p_program','parser.py',21),
  ('program -> PROGRAM ID PUNTO_COMA bloque','program',4,'p_program','parser.py',22),
  ('vars -> VAR vars2','vars',2,'p_vars','parser.py',26),
  ('vars2 -> ID vars3','vars2',2,'p_vars2','parser.py',28),
  ('vars3 -> COMA vars2','vars3',2,'p_vars3','parser.py',30),
  ('vars3 -> ASIGNACION TIPO PUNTO_COMA vars2','vars3',4,'p_vars3','parser.py',31),
  ('vars3 -> ASIGNACION TIPO PUNTO_COMA','vars3',3,'p_vars3','parser.py',32),
  ('bloque -> CORCHETE_IZQ bloque2 CORCHETE_DER','bloque',3,'p_bloque','parser.py',36),
  ('bloque2 -> estatuto','bloque2',1,'p_bloque2','parser.py',38),
  ('bloque2 -> estatuto bloque2','bloque2',2,'p_bloque2','parser.py',39),
  ('estatuto -> asignacion','estatuto',1,'p_estatuto','parser.py',42),
  ('estatuto -> condicion','estatuto',1,'p_estatuto','parser.py',43),
  ('estatuto -> escritura','estatuto',1,'p_estatuto','parser.py',44),
  ('asignacion -> ID ASIGNACION expresion PUNTO_COMA','asignacion',4,'p_asignacion','parser.py',47),
  ('escritura -> ESCRITURA PARENTESIS_IZQ escritura2 PARENTESIS_DER PUNTO_COMA','escritura',5,'p_escritura','parser.py',50),
  ('escritura2 -> expresion','escritura2',1,'p_escritra2','parser.py',53),
  ('escritura2 -> expresion COMA escritura2','escritura2',3,'p_escritra2','parser.py',54),
  ('escritura2 -> STRING','escritura2',1,'p_escritra2','parser.py',55),
  ('escritura2 -> STRING COMA escritura2','escritura2',3,'p_escritra2','parser.py',56),
  ('expresion -> exp','expresion',1,'p_expresion','parser.py',60),
  ('expresion -> exp EXPRESION exp','expresion',3,'p_expresion','parser.py',61),
  ('exp -> termino','exp',1,'p_exp','parser.py',65),
  ('exp -> termino EXP termino','exp',3,'p_exp','parser.py',66),
  ('termino -> factor','termino',1,'p_termino','parser.py',70),
  ('termino -> factor TERMINO factor','termino',3,'p_termino','parser.py',71),
  ('var_cte -> ID','var_cte',1,'p_var_cte','parser.py',74),
  ('var_cte -> ENTERO','var_cte',1,'p_var_cte','parser.py',75),
  ('var_cte -> FLOTANTE','var_cte',1,'p_var_cte','parser.py',76),
  ('condicion -> IF PARENTESIS_IZQ expresion PARENTESIS_DER condicion2','condicion',5,'p_condicion','parser.py',80),
  ('condicion2 -> bloque PUNTO_COMA','condicion2',2,'p_condicion2','parser.py',83),
  ('condicion2 -> bloque ELSE bloque PUNTO_COMA','condicion2',4,'p_condicion2','parser.py',84),
  ('factor -> PARENTESIS_IZQ expresion PARENTESIS_DER','factor',3,'p_factor','parser.py',88),
  ('factor -> var_cte','factor',1,'p_factor','parser.py',89),
  ('factor -> EXP var_cte','factor',2,'p_factor','parser.py',90),
]
