#define ENTERO	   1 //[x]
#define ID	   	   2 //[x]
#define FLOTANTE   3 //[x]
#define STRING	   4 //[x]
#define TIPO	   5 //[x]
#define EXPRESION  6 //[x]
#define TERMINO	   7 //[x]
#define ESCRITURA  8 //[x]
#define ASIGNACION 9 //[x]
#define PROGRAM	   10 //[x]
#define EXP	       11//[x]
#define CONDICION  12//[x]
#define PARENTESIS 13//[x]
#define CORCHETE   14//[x]
#define PUNTO_COMA 15//[x]
#define ESPACIO    16//[x]
#define FIN_LINEA  17//[x^]
#define TAB	       18//[x^]
